### PR TITLE
Update Dockerfile to install ruby 2.2.1 from rvm

### PR DESCRIPTION
**Pull request by easternbloc**
The version being installed from yum is old (1.8) and is incompatible with a gemfile in fpm

### CODE REVIEW

**Comment by vaijab** [comment]
No no no please. We can get the right version of ruby without RVM.

**Comment by timgent** [comment]
Does it matter for this repo? It is a container that runs as a one off job to build an rpm.

Though if we were to change it are you thinking of something like this? https://gist.github.com/chiraggude/11128087

**Comment by ipedrazas** [comment]
This is the Dockerfile for `ruby:2.2`

https://github.com/docker-library/ruby/blob/90b6b506a4b495cd337115d9a2b4ba6f80c72004/2.2/Dockerfile

It's more or less like that gist.

**Comment by easternbloc** [comment]
Fair enough I'll do it sans rvm.

**Comment by timgent** [comment]
Just made the updates to do this without rvm... turns out centos:7 has a version of ruby that works with fpm so using that

**Comment by timgent** [comment]
I will raise a new PR as the title of this one does't really make sense now

**Pull request closed without merging**
